- docs/intro.rst
Improve example in getting started for handling both listening and a producer
> Improve getting started for -both- case

- websockets/server.py
Since 181acf3, full tracebacks are printed if a connection is reset
during handshake.  Connection resets are to be expected, even in
controlled environments.  Simply log them as info rather than warning,
and don't print a full traceback.
Closes #126.
> server: don't print exceptions for network errors during handshake

- docs/changelog.rst
- websockets/client.py
- websockets/http.py
- websockets/protocol.py
- websockets/server.py
- websockets/test_http.py
Given that websockets makes straightforward use of HTTP, that websocket
implementations can be expected not to exhibit legacy behaviors, and
that RFC 7230 deprecates this behavior, parsing HTTP is doable.
Thanks https://github.com/njsmith/h11 for providing some inspiration,
especially for translating the RFC to regular expressions and figuring
out some edge cases.
I expect the new implementation to be faster, since it has a much
tighter focus than the stdlib's general purpose MIME parser, and
possibly more secure, since it was written from the beginning with
security as a primary goal (with the caveat that it's new code,
which means it's more likely to have security issues).
Fix #19.
> Replace MIME parsing with custom HTTP parsing.

- docs/api.rst
- docs/cheatsheet.rst
- websockets/server.py
Addresses issue #203.
One documentation change included in this PR that is less self-explanatory is changing `asyncio.BaseEventLoop.create_server` throughout the docs to `asyncio.AbstractEventLoop.create_server`. This fixes the hyperlinking to the Python docs, which wasn't working before (and since the docs say [not to use BaseEventLoop](https://docs.python.org/3/library/asyncio-eventloop.html#asyncio.BaseEventLoop) anyway).
> Address issue #203: make WebSocketServer not inherit

- websockets/speedups.c
Fixes aaugustin/websockets#223
> Correctly read mask in non SSE2 cases in speedups.c

- websockets/speedups.c
The code in speedups.c relies on the assumption that Python.h includes
stdint.h
This might change in the future or might not be the case on some platforms so don’t rely on this assumption.
> Don't rely on Python.h to include stdint.h in speedups.c

- websockets/speedups.c
Compiler is not smart enough to know that both operands are positive &
optimize this with masking. We do what it should have been doing.
This is not critical given that only the remainder (at most 7 bytes) is impacted but nevertheless.
> Replace modulo on signed integers by masking

- websockets/speedups.c
Only non-mutable bytes-like objects shall be supported
> Don't accept Unicode objects in speedups.apply_mask

- docs/conf.py
When I run `make html` from the docs directory, the output shows this:
Running Sphinx v1.6.3
loading pickled environment... done
loading intersphinx inventory from http://docs.python.org/3/objects.inv...
intersphinx inventory has moved: http://docs.python.org/3/objects.inv ->
https://docs.python.org/3/objects.inv
> Update intersphinx_mapping setting.

- docs/api.rst
- docs/changelog.rst
- docs/cheatsheet.rst
- websockets/client.py
- websockets/server.py
- websockets/test_client_server.py
This addresses issue #216.
One minor note: you'll notice in the signatures that I made the default value `None` instead of the default class. The reason is that this makes the API somewhat friendlier when it comes to composing functions, etc. For example, if an end user defines a wrapper function and wants the same default, they can get the same default by passing `None`. They don't need to hard-code the default value in a second place. Secondarily, when it comes to deciding between `create_protocol` and `klass`, this makes it easier to know which arguments were explicitly passed.
> Address issue #216: rename the klass argument to create_protocol.

- docs/api.rst
- docs/changelog.rst
- websockets/client.py
- websockets/compatibility.py
- websockets/exceptions.py
- websockets/http.py
- websockets/server.py
- websockets/test_client_server.py
This replaces the get_response_status() API which never made it into a
release (so there's no backwards incompatibility).
Remove a test that depends on get_response_status() being called after
check_request(). The extension point must be before check_request() so
it can handle regular HTTP requests.
Fix #116.
Supersedes #202 #154, #137.
> Add process_request() to override request handling.

- .travis.yml
- appveyor.yml
- setup.py
This is an attempt (WIP) to build wheels on various platforms using [cibuildwheel](https://github.com/joerick/cibuildwheel) on [travis-ci](https://travis-ci.org) & [appveyor](https://ci.appveyor.com)
So far, wheels are built on all platforms but nothing is done with them.
Results are here:
https://travis-ci.org/mayeut/websockets
https://ci.appveyor.com/project/mayeut/websockets
Known limitations:
- if the C extension build fails, a wheel will be built anyway as was the case for python 3.3 & 3.4 on Windows before 47b95195a28491ad4bfb0925560426bc38e7b8c0 (C extension configured as optional in setup.py)
- tests are not run because of failures
- `test_close_handshake_timeout` fails on macOS with error `AssertionError: 0.03943201599997792 not less than 0.029 : Too slow: 0.03943201599997792 >= …
> Address issue #220: Build wheels on various platforms

- README.rst
This reflects at first glance that this package is available on PyPI and that CI is in place.
I think that adding TravisCI and AppVeyor badges is not yet something that should be done. Not until wheels can be tested on those platforms.
In my opinion, a codecov badge wouldn't hurt as well c.f. #222. With that, at first glance, people will know package is available on PyPI, tested by CI and that coverage is 100%.
This, I think, is part of marketing tools (people knowing the project already know all of this).
Relates to #245
> Add PyPI and CircleCI badges to README

- circle.yml
Upload coverage results to `codecov` after `circleci` tests.
Overview here: https://codecov.io/gh/mayeut/websockets/tree/circleci-codecov/websockets
Python only for now.
Relates to #222, #245, #252
> Add codecov to circleci.yml

- websockets/client.py
- websockets/protocol.py
- websockets/server.py
- websockets/test_client_server.py
- websockets/test_protocol.py
While trying to document the `opening_handshake` and `closing_handshake` futures, I discovered they didn't actually served a purpose.
`connection_closed` does serve a purpose, but I took this opportunity to reconsider how connections are closed. I reworked the implementation and fixed some RFC-compliance problems.
> Remove futures & rework connection termination

- example/oldshutdown.py
- example/shutdown.py
Replaced "pass" statement by "break" inside echo handler loop.
If a client closes connection it causes an infinite loop and took 100% CPU.
"websocket.recv()" always throws "websockets.ConnectionClosed" so "pass" statement just
continue loop over and over again.
> Fixed infinite loop in "Graceful Shutdown" Examples when client closed the connection

- setup.py
add `zip_safe=True` to setup.py to tell easy_install and setuptools that the code should not be analyzed before installing.
This avoids the problem caused by evaluating code in the /websockets/py36/ directory when running under Python 3.5.
Fixes #341
> Add zip_safe=True to setup.py

- docs/changelog.rst
- docs/cheatsheet.rst
- docs/deployment.rst
- docs/intro.rst
- websockets/client.py
- websockets/py35/_test_client_server.py
- websockets/server.py
Clarify documentation about unsupported features in older Pythons.
Fix #318.
> Disable async context manager functionality on Python 3.5.

- docs/deployment.rst
- example/health_check_server.py
> Add an example of health check.

- docs/changelog.rst
- websockets/protocol.py
There's no need to print a full stack trace when the network connection
dropped earlier than we expected. A 1006 close code is likely sufficient
to identify the cause if this is an issue in actual deployments.
Fix #348, #349.
> Better handle hard TCP connection termination.

- websockets/compatibility.py
- websockets/exceptions.py
- websockets/handshake.py
- websockets/headers.py
- websockets/server.py
- websockets/test_client_server.py
- websockets/test_exceptions.py
- websockets/test_handshake.py
- websockets/test_headers.py
When receiving HTTP requests to WS endpoints:
- Avoid polluting logs at the warning level — but keep logs at the debug level because it must be possible to debug failures
- Return a HTTP 426 status code to plain HTTP requests
> Improve handling of HTTP requests.

- docs/changelog.rst
- websockets/protocol.py
- websockets/py36/_test_client_server.py
- websockets/py36/protocol.py
Quite often, browsers close WebSocket connections when the user
navigates to another page. In most cases this isn't an error
condition and thus not worth reporting with an exception.
> Don't treat close code 1001 as an error.

- docs/changelog.rst
- docs/design.rst
- websockets/client.py
- websockets/protocol.py
- websockets/server.py
- websockets/test_protocol.py
Mainly:
- Attach the reason why the connection was closed to ConnectionClosed exceptions
- Better mirror the specification in the implementation and improve compliance slightly in some edge cases
> Improve failing the WebSocket connection.

- websockets/client.py
- websockets/py35/_test_client_server.py
- websockets/server.py
- websockets/test_client_server.py
> Support yield from connect/serve on Python 3.7.

- .appveyor.yml
This was configured in the UI, however the UI is ignored when there's a
YAML config file.
> Prevent duplicate AppVeyor builds.

- websockets/__main__.py
This does the required calls to enable VT100 mode on Windows. Not sure if this matches your style-guide, feel free to adjust however you like.
With those patches applied, it now also works well on Windows.
> Enable VT100 support on Windows

- docs/changelog.rst
- src/websockets/protocol.py
- tests/test_protocol.py
> Make it possible to fragment outgoing messages.

- docs/changelog.rst
- docs/cheatsheet.rst
- docs/design.rst
- src/websockets/exceptions.py
- src/websockets/framing.py
- src/websockets/protocol.py
- src/websockets/server.py
- tests/test_client_server.py
- tests/test_framing.py
- tests/test_protocol.py
Previously, there were two scenarios where a connection handler on the
server side would receive an unexpected connection termination:
1. When the remote endpoint closed the connection or it dropped for any
reason: this was signalled with a ConnectionClosed exception when
interacting with the connection, usually thrown by recv() since most
connection handlers spend the majority of their time awaiting recv()
2. When the server shut down: this caused the connection handler to be
cancelled, meaning that a CancelledError exception was injected at
an arbitrary location.
Now, when the server shuts down, the scenario 1 also applies. This
removes the need to prepare for CancelledError in connection handlers.
A good way to understand this change is to consider that "shutting down
the server" means …
> Simplify connection termination on server shutdown.

- docs/changelog.rst
- src/websockets/client.py
- src/websockets/compatibility.py
- src/websockets/exceptions.py
- src/websockets/py35/client.py
- tests/test_client_server.py
Per https://tools.ietf.org/html/rfc6455.html#section-4.2.2 the server may redirect the client during the handshake. This allows the client to handle redirects properly instead of raising an InvalidStatusCode error.
> Handle redirects in client when connecting

- docs/changelog.rst
- example/health_check_server.py
- src/websockets/server.py
- tests/test_client_server.py
b64fee8e made it possible to use either a function or a coroutine. It
was part of the 7.0 release.
4f1a14c3 documented this possibility but wasn't released. However, users
may have read the "latest" docs and taken advantage of this.
For this reason, include proper deprecation warnings and preserve
backwards-compatibility (for the foreseeable future).
The deprecation warnings need to be in two locations to account for
passing a process_request argument and for overriding the
process_request method.
Issue #597 shows that `isinstance(..., Awaitable)` is more robust than
`asyncio.iscoroutinefunction(...)` because it also supports functions
returning awaitables.
> Change process_request to be a coroutine (again).

- docs/changelog.rst
- src/websockets/protocol.py
- tests/test_protocol.py
Fix #551.
Thanks @Harmon758 for diagnosing the root cause and proposing a fix.
> Handle ConnectionClosed exception in keepalive_ping.

- src/websockets/protocol.py
- tests/test_protocol.py
This is a bit of a hack: it relies on the implementation of asyncio.
Fix #637.
> Avoid logging ping exceptions that aren't retreived.

- .circleci/config.yml
- docs/changelog.rst
- setup.py
- src/websockets/__init__.py
- src/websockets/__main__.py
- src/websockets/client.py
- src/websockets/framing.py
- src/websockets/handshake.py
- src/websockets/protocol.py
- src/websockets/server.py
- tests/__init__.py
- tests/test_client_server.py
- tests/test_framing.py
- tests/test_protocol.py
- tox.ini
> Add support for Python 3.8

- src/websockets/__init__.py
- tests/test_exports.py
fixes #679 
Also adds a test to make sure no two names are competing with each other in the top-level namespace (e.g. two sub-modules can't export the same name).
> Hardcode top-level exports.

- src/websockets/http.py
When dealing with version numbers, it's generally safer to use the `sys.version_info` tuple that the `sys.version` string.
```pycon
>>> sys.version
'3.7.5 (default, Nov  1 2019, 02:16:32) \n[Clang 11.0.0 (clang-1100.0.33.8)]'
>>> sys.version[:3]
'3.7'
>>> fake_version310_info = '3.10.5 (default, Nov  1 2019, 02:16:32) \n[Clang 11.0.0 (clang-1100.0.33.8)]'
>>> fake_version310_info[:3]
'3.1'
```
When Python 3.10 comes around (probably in [May 2020 when Python 3.9 reaches beta](https://www.python.org/dev/peps/pep-0596/#schedule)), it will claim to be on Python 3.1!
With the version tuple:
```pycon
>>> "{}.{}".format(3, 7)
'3.7'
>>> "{}.{}".format(3, 10)
'3.10'
```
Found with https://github.com/asottile/flake8-2020.
> Fix for Python 3.10: use sys.version_info instead of sys.version

- src/websockets/client.py
- src/websockets/server.py
There is a small typo in src/websockets/client.py, src/websockets/server.py.
Should read `several` rather than `severel`.
> Fix simple typo: severel -> several

- .circleci/config.yml
- .gitignore
- src/websockets/server.py
- tox.ini
> Future-proof asyncio.wait usage.

- src/websockets/server.py
I recently went over [Matplotlib](https://github.com/matplotlib/matplotlib/pull/16706), [Pandas](https://github.com/pandas-dev/pandas/pull/32322) and [NumPy](https://github.com/numpy/numpy/pull/15731), fixing a small mistake in the way that Python 3's exception chaining is used. If you're interested, I can do it here too. I've done it on just one file right now. 
The mistake is this: In some parts of the code, an exception is being caught and replaced with a more user-friendly error. In these cases the syntax `raise new_error from old_error` needs to be used.
Python 3's exception chaining means it shows not only the traceback of the current exception, but that of the original exception (and possibly more.) This is regardless of `raise from`. The usage of `raise from` tells Python to put a …
> Fix exception causes in server.py

- .travis.yml
TravisCI allows creation of arm64 wheels.
Build log: https://travis-ci.com/github/janaknat/websockets/jobs/375133111
> Add aarch64 wheel build

- docs/changelog.rst
- src/websockets/legacy/server.py
- tests/extensions/test_permessage_deflate.py
> Support serve() with existing Unix socket.

- src/websockets/legacy/protocol.py
- tests/legacy/test_protocol.py
When the read buffer isn't empty, the following scenario is possible:
* TCP connection is closed (one way or another)
* transfer_data is still processing buffered data
* it encounters a ping and attempts to send a pong
transfer_data must never crash, so ignore the error in this case.
Fix #977
> Prevent crash of data transfer task

- docs/howto/logging.rst
- docs/project/changelog.rst
- docs/spelling_wordlist.txt
- src/websockets/legacy/client.py
- src/websockets/legacy/server.py
- tests/legacy/test_client_server.py
> Add support for reconnecting automatically.

- src/websockets/utils.py
This speeds up the Python version of `utils.apply_mask` about 20 times, using `int.from_bytes` so that the XOR is done in a single Python operation -- in other words, the loop over the bytes is in C rather than in Python.
Note that it is a trade-off as it uses more memory: this version allocates roughly `len(data)` bytes for each of the intermediate values (e.g., data_int, mask_repeated, mask_int, the XOR result); whereas I believe the original version only allocates for the return value.
Still, most websocket packets aren't huge, and I believe the massive speed gain here makes it worth it. (And people that use the speedups.c version won't be affected.)
Obviously the speedups.c version is still significantly faster again, but this change makes the library more usable in environments when …
> Speed up Python apply_mask 20x by using int.from_bytes/to_bytes

- .github/workflows/tests.yml
- src/websockets/legacy/protocol.py
- tests/legacy/test_client_server.py
> Unpin Python 3.9.6.

- src/websockets/legacy/protocol.py
- tests/legacy/test_protocol.py
> Avoid shutdown on closed socket.

- src/websockets/version.py
Allow version check to ignore `git` if the command is not available on the path.
> Don't rely on `git` being on the path

- tests/test_utils.py
PyPy3.9 7.3.9 does not implement creating contiguous buffers from
non-contiguous, causing the respective tests to fail due to
NotImplementedError.  Catch it and skip the tests appropriately
as discussed in #1157.
> Skip non-contiguous buffer tests on NotImplementedError (pypy)

- src/websockets/legacy/protocol.py
Due to context switch during `await self.write_frame(True, OP_PING, data)` in the ping method, the relevant key in self.pings gets deleted resulting in a KeyError at `return asyncio.shield(self.pings[data])`, which in turn crashes the keepalive_ping task.
https://github.com/aaugustin/websockets/blob/c4a4b6f45af607431c5707d56420bbaf471bbb6e/src/websockets/legacy/protocol.py#L849-L853
This bug can be consistently reproduced while sending a fragmented message (the first keepalive ping always fails during my tests).
> Fix unsafe reference to self.pings with a variable

- src/websockets/legacy/protocol.py
- src/websockets/legacy/server.py
- tests/legacy/test_protocol.py
- tests/legacy/utils.py
There are small typos in:
- src/websockets/legacy/protocol.py
- src/websockets/legacy/server.py
- tests/legacy/test_protocol.py
- tests/legacy/utils.py
Fixes:
- Should read `suspect` rather than `supect`.
- Should read `acknowledged` rather than `acknowleged`.
- Should read `attempts` rather than `attemps`.
- Should read `asynchronous` rather than `asychronous`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md
> docs: Fix a few typos

- src/websockets/uri.py
Hello!
Due to the nature of dataclasses in Python, for a field to be truly optional, it must be provided with a default value, not only `Optional` annotation. Otherwise, when creating `WebSocketURI` сlass instance without `login` and `password`, we will get an error like:
```
TypeError: WebSocketURI.init() missing 2 required positional arguments: 'username' and 'password'
```
Judging by the code, this was an accidental oversight, because checking for `None` value of the `name` and `password` already exists and the rest of the project code has default values for dataclasses.
Thanks in advance.
> Default values for Optional fields in WebSocketURI

- src/websockets/legacy/auth.py
- src/websockets/legacy/client.py
- src/websockets/legacy/server.py
`[Any]` means one argument of `Any` type, `...` means "ignore". This is relevant since `WebSocketServerProtocol` and similar in fact have multiple arguments. Ideally a `Protocol` with a `__call__` method included should be used, but that's up for discussion since that would add maintainability issues as the signature would be duplicated in multiple places.
**Or**, `Type[WebSocketServerProtocol]` *may* work too.
> Refactor create_protocol to represent the real type

- src/websockets/legacy/client.py
`create_connection` requires either `host` or `server_hostname` if `ssl` is truthy. If `sock` is given, `host` gets unset, so provide `server_hostname` with the URI host if needed and not already provided by the caller.
> Set server_hostname automatically when needed

- docs/faq/common.rst
- docs/topics/design.rst
- pyproject.toml
- src/websockets/legacy/async_timeout.py
- src/websockets/legacy/client.py
- src/websockets/legacy/compatibility.py
- src/websockets/legacy/protocol.py
- src/websockets/legacy/server.py
- tests/legacy/test_client_server.py
- tests/legacy/test_protocol.py
`asyncio.wait_for` creates a task whereas `asyncio.timeout` avoids doing this which decreases latency.
Fallback to using `async_timeout` when the python version is too old (<3.11)
`asyncio.timeout` will become the underlying implementation for `async.wait_for` in cpython 3.12
https://github.com/python/cpython/pull/98518
> Switch to using asyncio.timeout instead of asyncio.wait_for

- pyproject.toml
- src/websockets/sync/server.py
For a senior-level university network apps design course, my students were using the threaded version of `WebSocketServer` as part of their final project. While the project required their work to run successfully in containers on Linux, many of them use Windows for their development workstation. We discovered that `serve_forever` throws an error at startup on Windows due to the use of `select.poll` as the means to block while waiting for incoming socket connections. The documentation for `poll` indicates that it is not supported on all platforms, and apparently Windows is one such platform.
I patched `WebSocketServer` to instead use `selectors.DefaultSelector` which determines the best supported mechanism for I/O multiplexing on the runtime platform. The functionality is the same, but it …
> Use selectors instead of select.poll in sync.WebSocket Server for multi-platform support

- .github/workflows/wheels.yml
> Create GitHub release when pushing tag.

- README.rst
Please let me know if I'm missing something making this import useful in this code snippet.
> Remove the unused `asyncio` import in `README.rst` in the `threading` example

- tests/utils.py
It is desirable to be able to set `WEBSOCKETS_TESTS_TIMEOUT_FACTOR` to a floating point value like `1.1`.
> test: allow WEBSOCKETS_TESTS_TIMEOUT_FACTOR to be float

- src/websockets/legacy/client.py
- tests/test_protocol.py
While studying the websockets source code, I found an incorrect RFC number in the comments and test docstrings.
- Incorrect: [RFC 6544](https://datatracker.ietf.org/doc/html/rfc6544) TCP Candidates with Interactive Connectivity Establishment (ICE)
- Correct: [RFC 6455](https://datatracker.ietf.org/doc/html/rfc6455) The WebSocket Protocol
I did this keyword search and fixed everything.
I truly appreciate your efforts in maintaining this fantastic library!
> Fix wrong RFC number

- docs/howto/nginx.rst
Hey, thanks for the project. I'm reading the docs these days (they're very well made, thanks for this), and I found just this small typo.
> docs(nginx): Fix a typo

- src/websockets/legacy/protocol.py
When enabling raise_exceptions in the broadcast method the code will always return an exception without this change
> Correct handle exceptions in `legacy/broadcast`

- docs/faq/server.rst
- src/websockets/legacy/server.py
It seems that `server.close()` is not an `async` function, so I changed
```python
await server.close()
```
to
```python
server.close()
await server.wait_closed()
```
in the API reference.
> docs: Correct the example for "Starting a server" in the API reference

- tests/utils.py
Nowadays it's tuned with WEBSOCKETS_TESTS_TIMEOUT_FACTOR.
> Reduce MS for situations with performance penalties.

- docs/project/changelog.rst
- src/websockets/asyncio/client.py
- src/websockets/asyncio/server.py
- src/websockets/server.py
- src/websockets/sync/server.py
- tests/asyncio/test_server.py
- tests/sync/test_server.py
- tests/test_server.py
> Stop if process_request/response aborts the opening handshake.

- docs/project/changelog.rst
- src/websockets/asyncio/connection.py
- src/websockets/sync/connection.py
> Wait until state is CLOSED to acces close_exc.

- src/websockets/asyncio/connection.py
- tests/asyncio/test_connection.py
> Add option to force sending text or binary frames.

- docs/project/changelog.rst
- src/websockets/asyncio/client.py
- src/websockets/asyncio/messages.py
- src/websockets/asyncio/server.py
- src/websockets/sync/client.py
- src/websockets/sync/connection.py
- src/websockets/sync/messages.py
- src/websockets/sync/server.py
- tests/asyncio/test_connection.py
- tests/asyncio/test_messages.py
- tests/sync/test_connection.py
- tests/sync/test_messages.py
Previously, a latch was used to synchronize the user thread reading messages and the background thread reading from the network. This required two thread switches per message.
Now, the background thread writes messages to queue, from which the user thread reads. This allows passing several frames at each thread switch, reducing the overhead.
With this server code::
async def test(websocket):
for i in range(int(await websocket.recv())):
await websocket.send(f"{{\"iteration\": {i}}}")
and this client code::
with connect("ws://localhost:8765", compression=None) as websocket:
websocket.send("1_000_000")
for message in websocket:
pass
an unscientific benchmark (running it on my laptop) shows a 2.5x speedup, going from 11 seconds to 4.4 seconds. Setting a very large recv_bufsize and max_size …
> Rewrite sync Assembler to improve performance.

- docs/project/changelog.rst
- src/websockets/asyncio/client.py
- src/websockets/asyncio/connection.py
- src/websockets/asyncio/messages.py
- src/websockets/asyncio/server.py
- src/websockets/sync/client.py
- src/websockets/sync/connection.py
- src/websockets/sync/messages.py
- src/websockets/sync/server.py
- tests/asyncio/test_connection.py
- tests/asyncio/test_messages.py
- tests/sync/test_connection.py
- tests/sync/test_messages.py
> Support max_queue=None like the legacy implementation.

- docs/reference/asyncio/client.rst
- docs/reference/asyncio/common.rst
- docs/reference/asyncio/server.rst
- docs/reference/sync/client.rst
- docs/reference/sync/common.rst
- docs/reference/sync/server.rst
- src/websockets/asyncio/connection.py
- src/websockets/protocol.py
- src/websockets/sync/connection.py
- tests/asyncio/test_connection.py
- tests/sync/test_connection.py
Also add state to threading implementation.
Fix #1537.
> Add close_code and close_reason to new implementations.

- src/websockets/client.py
- src/websockets/http11.py
- src/websockets/server.py
- tests/test_client.py
- tests/test_http11.py
- tests/test_server.py
> Read chunked HTTP responses.

- docs/project/changelog.rst
- src/websockets/sync/messages.py
- tests/sync/test_messages.py
> Fix Connection.recv(timeout=0) in the sync implementation.

- src/websockets/asyncio/server.py
- src/websockets/server.py
- src/websockets/sync/server.py
- tests/test_server.py
Hello. In my project I tried to pass a regular expression to `origins`, but it didn't work.
I think this will not be superfluous for the project.
Idea taken from [https://github.com/corydolphin/flask-cors/blob/main/flask_cors/core.py](https://github.com/corydolphin/flask-cors/blob/main/flask_cors/core.py)
> Add regex support in `ServerProtocol(origins=...)`

- docs/project/changelog.rst
- pyproject.toml
- src/websockets/__init__.py
- src/websockets/asyncio/connection.py
- src/websockets/asyncio/messages.py
- src/websockets/sync/connection.py
- src/websockets/sync/messages.py
- src/websockets/typing.py
> Add type overloads for recv and recv_streaming.

- docs/project/changelog.rst
- docs/reference/features.rst
- docs/topics/proxies.rst
- src/websockets/asyncio/client.py
- src/websockets/headers.py
- src/websockets/http11.py
- src/websockets/sync/client.py
- src/websockets/sync/server.py
- tests/asyncio/test_client.py
- tests/proxy.py
- tests/sync/test_client.py
- tests/test_headers.py
- tests/test_http11.py
- tests/test_uri.py
- tests/utils.py
- tox.ini
> Add support for HTTP(S) proxies to clients.

- README.rst
The primary README has an invalid import in the asyncio example.
Changes:
- `serve` is now correctly imported from `websockets.asyncio.server`
> Fix incorrect asyncio import in README

- pyproject.toml
Thank you for this amazing package! 
I find my self using the interactive client tool often, which is a great way to quickly test out my websocket server. 
Currently I would need to have activated an environment with websockets installed to be able to run the interactive client.
I would love the ability to run the client as a global tool, and think this workflow is now more mainstream with tools like uv and pipx. 
Defining an entry point in pyproject.toml will enable use of the interactive client with both uv tool/uvx and pipx. 
One issue though:
I tested it out locally and it works with uv. However it does not handle keyboard interrupts properly and does not close the connection gracefully. I can't seem to figure out where the issue is, since there is an exception handler for keyboard …
> Define Entry Point in pyproject.toml

- src/websockets/http11.py
- tests/test_http11.py
Shelly devices send a 'Content-Length' header with a value of "0". Allow this as this also means there is not a request body.
In addition give a bit more detail in the error message.
Closes: #1616
> fix: allow 'Content-Length' = "0"

- docs/project/changelog.rst
- src/websockets/asyncio/client.py
- src/websockets/http11.py
- src/websockets/sync/client.py
- tests/test_http11.py
It is legal to answer an HTTP/1.1 request with an HTTP/1.0 response.
Fix #1609.
> Add support for HTTP/1.0 proxies.

- docs/faq/misc.rst
- docs/project/changelog.rst
- src/websockets/asyncio/client.py
- src/websockets/asyncio/connection.py
- src/websockets/asyncio/server.py
- src/websockets/client.py
- src/websockets/exceptions.py
- src/websockets/protocol.py
- src/websockets/server.py
- src/websockets/sync/client.py
- src/websockets/sync/connection.py
- src/websockets/sync/server.py
- tests/test_protocol.py
> Support separate limits for messages and fragments.
