- docs/index.rst
- websockets/client.py
- websockets/protocol.py
- websockets/server.py
> Support non-default event loop.

- docs/index.rst
- websockets/client.py
- websockets/protocol.py
- websockets/server.py
- websockets/test_client_server.py
> Add support for subprotocols.

- websockets/protocol.py
- websockets/test_protocol.py
They are no timeout argument on ``websocket.recv()`` also when using it with:
yield from asyncio.wait_for(websocket.recv(), 5)
The task is canceled but the next message on the websocket is not received by the next ``websocket.recv()`` call.
> Timeout on websocket.recv()

- docs/changelog.rst
- docs/intro.rst
- example/sendtime.py
- example/server.py
> Update docs to async / await syntax.

- websockets/server.py
As I need to use this function from the outside (feel free to ask why if you want to) and the method can be static, I've made it static. Nothing special. :)
> Make select_subprotocol a static method

- websockets/http.py
> Fix read_response when reason is empty

- websockets/protocol.py
Works around the following error:
File /usr/lib/python3.4/asyncio/streams.py, line 194, in _drain_helper
assert waiter is None or waiter.cancelled()
AssertionError
> protocol: add a lock around StreamWriter.drain(), closes #16

- docs/changelog.rst
- docs/deployment.rst
- example/oldshutdown.py
- websockets/client.py
- websockets/py35/client_server.py
- websockets/py35/server.py
- websockets/server.py
> Make serve an async context manager.

- .gitignore
- Makefile
- docs/changelog.rst
- setup.py
- tox.ini
- websockets/framing.py
- websockets/speedups.c
- websockets/test_utils.py
- websockets/utils.py
Thanks Messense Lv (@messense) and Matthieu Darbois (@mayeut) for proposing previous iterations of this patch in #175 and #211.
> Speed up frame (un)masking with a C extensions.

- docs/api.rst
This adds max_queue to WebSocketCommonProtocol in api.rst.
> Fix api.rst

- websockets/test_client_server.py
> Address issue #218: ensure server stopped in tests

- websockets/test_client_server.py
This provides a treatment similar to PR #219, but for the client. It reduces boilerplate in tests and ensures the client is stopped even on test failure.
> Add with_client() test method decorator.

- websockets/test_client_server.py
This uses the `temp_client()` context manager in the few remaining places we call `stop_client()`.
(I missed these the first time around because I was focusing on the places where we can use the decorator form.)
> Use temp_client() where we can't use the with_client() decorator.

- .travis.yml
- README.rst
- appveyor.yml
- circle.yml
- docs/index.rst
- docs/intro.rst
- setup.cfg
- setup.py
- tox.ini
- websockets/extensions/test_permessage_deflate.py
- websockets/extensions/test_utils.py
- websockets/extensions/utils.py
- websockets/http.py
- websockets/test_client_server.py
- websockets/test_framing.py
- websockets/test_uri.py
- websockets/test_utils.py
> Drop support for Python 3.3.

- docs/api.rst
- websockets/client.py
- websockets/extensions/test_permessage_deflate.py
- websockets/headers.py
- websockets/http.py
- websockets/server.py
- websockets/test_client_server.py
- websockets/test_headers.py
> Parse Sec-WebSocket-Protocol robustly.

- docs/design.rst
- websockets/protocol.py
- websockets/test_protocol.py
> Handle clogged pipes in close() 

- README.rst
> Add marketing copy to the README.

- docs/changelog.rst
- websockets/client.py
- websockets/test_client_server.py
Fix #221.
(from PR #229, edited by the committer).
> Add support for sock argument in client.

- docs/api.rst
- docs/changelog.rst
- websockets/server.py
- websockets/test_client_server.py
> Add unix_server to create a Unix server.

- websockets/test_client_server.py
Fix #215.
Thanks @cjerdonek for reporting and investigating this issue.
> Test ConnectionError handling.

- docs/api.rst
- docs/changelog.rst
- websockets/protocol.py
- websockets/test_protocol.py
> Manage connection states with an enum.

- docs/api.rst
- docs/changelog.rst
- websockets/py35/_test_client_server.py
- websockets/py36/_test_client_server.py
- websockets/server.py
- websockets/test_client_server.py
Also refactor tests to bind to an arbitrary available port instead of
hardcoding port 8642.
> Add WebSocketServer.sockets.

- websockets/compatibility.py
> Fix Syntax error thrown in 3.7

- docs/changelog.rst
- websockets/py35/_test_client_server.py
- websockets/server.py
- websockets/test_client_server.py
> Make unix_serve an asynchronous context manager.

- docs/changelog.rst
- websockets/client.py
- websockets/http.py
- websockets/test_client_server.py
- websockets/test_http.py
- websockets/test_uri.py
- websockets/uri.py
> Add support for HTTP Basic Auth in the client side.

- websockets/client.py
- websockets/server.py
> Improve description of connect and serve.

- websockets/server.py
> Document that handlers can be cancelled.

- docs/changelog.rst
- websockets/protocol.py
- websockets/test_protocol.py
> Fix a race condition in the closing handshake.

- docs/changelog.rst
- websockets/client.py
- websockets/py35/_test_client_server.py
- websockets/py35/client.py
- websockets/py35/server.py
- websockets/server.py
- websockets/test_client_server.py
Hopefully for real this time.
This is annoyingly complicated.
Fix #405.
> Add support for Python 3.7.

- docs/changelog.rst
- websockets/client.py
- websockets/handshake.py
- websockets/headers.py
- websockets/http.py
- websockets/protocol.py
- websockets/server.py
- websockets/test_client_server.py
- websockets/test_exceptions.py
- websockets/test_handshake.py
- websockets/test_headers.py
- websockets/test_http.py
> Refactor handling of HTTP headers.

- Makefile
- docs/changelog.rst
- docs/intro.rst
- tox.ini
- websockets/__main__.py
- websockets/exceptions.py
> Add an interactive client.

- docs/changelog.rst
- src/websockets/protocol.py
- tests/test_protocol.py
> Abort pending pings with ConnectionClosed.

- src/websockets/protocol.py
- tests/test_protocol.py
> Send fragmented messages from async iterators.

- src/websockets/protocol.py
> typo in documentation

- docs/changelog.rst
- src/websockets/exceptions.py
- src/websockets/protocol.py
- src/websockets/server.py
- tests/test_exceptions.py
Thanks @cjerdonek for the suggestion.
Fix #285.
> Add ConnectionClosed subclass for normal closure.

- docs/api.rst
- docs/changelog.rst
- example/basic_auth_client.py
- example/basic_auth_server.py
- src/websockets/__init__.py
- src/websockets/auth.py
- src/websockets/client.py
- src/websockets/headers.py
- tests/test_auth.py
- tests/test_client_server.py
- tests/test_headers.py
> Support HTTP Basic Auth on the server side.

- docs/changelog.rst
- docs/faq.rst
- docs/index.rst
> Add a FAQ.

- docs/changelog.rst
- src/websockets/client.py
- src/websockets/http.py
- src/websockets/server.py
- tests/test_http.py
> Improve HTTP parsing error messages.

- tests/test_http.py
- tests/utils.py
> Convert tests for HTTP parsing to async style.

- src/websockets/protocol.py
If writing is stuck (and closing the connection counts as a write),
then cancelling won't achieve anything. There's only one way out:
closing the connection, waiting until all timeouts elapse, and
eventually websockets gives up and aborts the TCP connection.
Fix #278.
> Discourage cancellation of APIs that write frames.

- tests/test_protocol.py
> Try to make tests less flaky.

- docs/changelog.rst
- src/websockets/protocol.py
- src/websockets/server.py
- tests/test_client_server.py
> Close connections properly in WebSocketServer.close.

- docs/api.rst
- docs/changelog.rst
- docs/spelling_wordlist.txt
- src/websockets/auth.py
- src/websockets/client.py
- src/websockets/extensions/base.py
- src/websockets/extensions/permessage_deflate.py
- src/websockets/framing.py
- src/websockets/handshake.py
- src/websockets/headers.py
- src/websockets/http.py
- src/websockets/protocol.py
- src/websockets/server.py
- src/websockets/typing.py
- src/websockets/uri.py
- src/websockets/utils.py
- tests/test_auth.py
> Improve API docs with info fields.

- src/websockets/exceptions.py
> Re-expose WebSocketProtocolError

- example/counter.py
Fixed an error of logging.error
> Fix typo in example/counter.py

- src/websockets/handshake_legacy.py
That should be the rest of them :)
> Fix exception causes in handshake.py

- setup.cfg
specifically I was looking for the Changelog      Changelog=https://websockets.readthedocs.io/en/stable/changelog.html
> add project_urls metadata

- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/issue.md
> Setup issue template

- src/websockets/client.py
- src/websockets/server.py
- tests/test_client.py
- tests/test_server.py
This can facilitate integration in other projects that bring
their own HTTP stack.
> Make it possibly to bypass the handshake.

- docs/howto/django.rst
- docs/howto/faq.rst
- docs/howto/haproxy.rst
- docs/howto/heroku.rst
- docs/howto/kubernetes.rst
- docs/howto/nginx.rst
- docs/howto/supervisor.rst
- docs/project/changelog.rst
- docs/reference/client.rst
- docs/reference/server.rst
- src/websockets/__main__.py
- src/websockets/connection.py
- src/websockets/exceptions.py
- src/websockets/frames.py
- src/websockets/legacy/framing.py
- src/websockets/legacy/protocol.py
- tests/extensions/test_permessage_deflate.py
- tests/legacy/test_framing.py
- tests/legacy/test_protocol.py
- tests/test_connection.py
- tests/test_exceptions.py
- tests/test_frames.py
> Add details to ConnectionClosed exceptions.

- README.rst
- compliance/test_server.py
- docs/howto/faq.rst
- docs/intro/index.rst
- docs/project/changelog.rst
- docs/topics/authentication.rst
- docs/topics/broadcast.rst
- example/basic_auth_server.py
- example/counter.py
- example/deployment/haproxy/app.py
- example/deployment/heroku/app.py
- example/deployment/kubernetes/app.py
- example/deployment/nginx/app.py
- example/deployment/supervisor/app.py
- example/django/authentication.py
- example/django/notifications.py
- example/echo.py
- example/health_check_server.py
- example/secure_server.py
- example/server.py
- example/show_time.py
- example/shutdown_server.py
- example/unix_server.py
- experiments/authentication/app.py
- experiments/broadcast/server.py
- experiments/compression/server.py
- src/websockets/legacy/server.py
- tests/legacy/test_client_server.py
Ensure backwards-compatibility.
Ref #1038.
> Remove path argument from connection handlers.

- .github/workflows/tests.yml
> Pin Python 3.9.6 in CI.

- src/websockets/client.py
- src/websockets/connection.py
- src/websockets/datastructures.py
- src/websockets/http11.py
- src/websockets/server.py
- src/websockets/speedups.c
Spotted a typo in a comment, then did a quick pass over the code base to fix some others for a PR.
> Fix some typos in comments

- tests/legacy/test_client_server.py
Fix the test failures reported in #1175.
> Fix Python 3.11 test failures

- src/websockets/legacy/server.py
> Don't log when connection drops during handshake.

- docs/faq/server.rst
- docs/project/changelog.rst
- src/websockets/legacy/server.py
- tests/legacy/test_client_server.py
> Add option keep connections open when closing server.

- .github/workflows/tests.yml
- Makefile
- setup.cfg
- src/websockets/exceptions.py
- tests/extensions/test_base.py
- tests/extensions/test_permessage_deflate.py
- tests/extensions/utils.py
- tests/legacy/test_client_server.py
- tests/maxi_cov.py
- tests/test_connection.py
- tests/test_exceptions.py
- tox.ini
This makes it possible to increase coverage threshold to "each module has 100% branch coverage from its own tests".
This implementation supports `make maxi_cov` and `tox -e maxi_cov`. It is also enabled in CI.
> Add a script to measure coverage per module.

- docs/project/changelog.rst
- docs/topics/logging.rst
- src/websockets/legacy/protocol.py
- tests/legacy/test_client_server.py
- tests/legacy/test_protocol.py
> Improve error handling in broadcast().

- .github/workflows/wheels.yml
- setup.py
> Build architecture independent wheels.

- docs/faq/common.rst
- docs/howto/django.rst
- docs/howto/fly.rst
- docs/howto/heroku.rst
- docs/howto/kubernetes.rst
- docs/howto/render.rst
- docs/project/changelog.rst
- docs/reference/datastructures.rst
- docs/topics/authentication.rst
- example/django/authentication.py
- example/django/notifications.py
- experiments/authentication/app.py
- src/websockets/exceptions.py
- src/websockets/frames.py
- src/websockets/legacy/protocol.py
- src/websockets/protocol.py
- src/websockets/sync/connection.py
- src/websockets/sync/server.py
- tests/extensions/test_permessage_deflate.py
- tests/legacy/test_client_server.py
- tests/legacy/test_framing.py
- tests/legacy/test_protocol.py
- tests/sync/test_connection.py
- tests/sync/test_server.py
- tests/test_exceptions.py
- tests/test_frames.py
- tests/test_protocol.py
> Provide an enum for close codes.

- src/websockets/protocol.py
- tests/test_protocol.py
> Allow sending ping and pong after close.

- src/websockets/client.py
- src/websockets/server.py
- tests/test_client.py
- tests/test_connection.py
- tests/test_server.py
Also refactor tests for Sans-I/O client and server.
> Improve exception handling during handshake.

- pyproject.toml
> Blind fix for coverage failing in GitHub Actions.

- docs/howto/patterns.rst
Hi.
I've just spotted a kind of typo is the docs.
> Docs. Correct Producer pattern example.
